openapi: 3.0.2
info:
  title: SBB Swiss Mobility API
  version: 3.26.2
paths:
  /xss:
    get:
      summary: XSS Vulnerability Test
      description: This endpoint is vulnerable to XSS.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: '{"xss": "<script>alert("XSS")</script>"}'
